name: Step 2
run-name: ¡Llegaron los trigger baby!
on:
  push: 
    branches:
      - 'main'
      - 'aprendiendo-github-actions'
    paths: 
      - '**.js'
  pull_request:
    types: [opened, labeled]
    branches:
      - 'aprendiendo-github-actions'
  issues:
    types:
      - labeled
jobs:
  hola-mundo:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.3.0
      - name: Correr script
        run: node hola_mundo.js
